name: development
channels:
  - defaults
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python
  - pip
  - ipython
  - ipykernel
  - pytorch
  - torchvision
  - torchaudio
  - pytorch-cuda
  - pip:
    - torch
    - torchvision
    - torchaudio
    - matplotlib
    - pandas
    - seaborn
    - opencv-python
    - scikit-learn
    - grad-cam
    - scikit-image
    - tensorboard
    - pytorch-wavelets
    - PyWavelets
    - transformers
    - ipywidgets
    - timm
    - wandb
    - patchify
    - tabulate
