[project]
name = "graph-xpci"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "torch",
    "torchvision",
    "torchaudio",
    "matplotlib",
    "pandas",
    "seaborn",
    "opencv-python",
    "scikit-learn",
    "grad-cam",
    "scikit-image",
    "tensorboard",
    "pytorch-wavelets",
    "PyWavelets",
    "transformers",
    "ipywidgets",
    "timm",
    "wandb",
    "patchify",
    "tabulate",
    "jupyterlab",
    "einops>=0.8.1",
    "torchmetrics>=1.7.2",
    "umap-learn>=0.5.9.post2",
    "segmentation-models-pytorch>=0.5.0",
    "albumentations>=2.0.8",
]
